// @ts-check
// Docusaurus sidebar configuration.
// The autogenerated sidebar builds itself from the docs/ folder structure,
// picking up `sidebar_position` from each doc and labels from _category_.json.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],

  // Prefer an explicit sidebar instead? Replace the block above with:
  // docsSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Guides',
  //     items: ['guides/generate-departure-trips'],
  //   },
  // ],
};

module.exports = sidebars;
